### ISSUE TITLE
Images do not show up at pkgdown site

### ISSUE THREAD

**Issue by zx8754** [johnmackintosh/runcharter#38]
https://johnmackintosh.github.io/runcharter/articles/runcharter.html

![image](https://user-images.githubusercontent.com/5212915/141129344-db9a8e0b-fa23-436f-bfa6-173e017cb1c5.png)

**Comment by johnmackintosh** [comment]
I changed to publishing from github pages and looks like things have gone missing. 
I've just set it back to the original location, looks ok to me now, having cleared my cache, re-knit docs and pushed back -  can you confirm @zx8754 ?

**Comment by zx8754** [comment]
Yep, can see the images.
