### ISSUE TITLE
Rework as a geom extension

### ISSUE THREAD

**Issue by md0u80c9** [johnmackintosh/runcharter#5]
Just having a read of the code. I wondered whether you'd considered trying to rework this as a geom extension. That would give you a lot more rendering flexibility and future-proofing.I must confess I haven't tried doing this myself.

https://ggplot2.tidyverse.org/articles/extending-ggplot2.html#creating-a-new-geom

The faceting stuff would then be superfluous entirely - you'd use standard ggplot2 facets to do that. All the customisation would be dictated using aes, and you'd end up with a very similar syntax to doing a standard geom_line plot.

**Comment by md0u80c9** [comment]
I've started work on doing this this evening (on md0u80c9/runcharter which is a fork from your main code).

I've reworked the run calculation code into a new ggplot2 stat called RunChartMedians. I've managed to get the median generating code into 120 lines including documentation.

I haven't tried faceting yet (you need to do that from ggplot2 itself), but I filtered a single ward from the signals dataset, and then I can now plot the baselines (not the projected ones) with the following two lines of code.

```
signals2 <- dplyr::filter(signals, "WardY")
ggplot(signals2, aes(date, y)) + geom_line() + stat_runchart_medians(geom="segment", colour = "orange")
```

The next step is to make a geom_runchart containing the plotting code.

**Comment by johnmackintosh** [comment]
as discussed, happy for you to work on the geom extension, I didn't have any plans to go down that route, but look forward to seeing what you develop
