### ISSUE TITLE
Clipped maxima / minima

### ISSUE THREAD

**Issue by md0u80c9** [johnmackintosh/runcharter#6]
Hi,

If your data is properly awful, you end up with some very horrid outliers which destroy the detail of the chart (the attached is an actual chart from my local data!)

The best way I've found to deal with this so far is to clip them by using pmin and pmax on the vector to set them as the top and bottom limit of the chart.

It might be quite nice to clip the chart and indicate where points have been clipped.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/3925834/56887708-2ae15980-6a6a-11e9-9d22-07163b345b11.png">

After clipping the three outliers:

Of course the clipping a) loses the fact that the first dot is a far worse outlier than the other two!

![image](https://user-images.githubusercontent.com/3925834/56887994-e30f0200-6a6a-11e9-8511-3768f9e27633.png)

**Comment by md0u80c9** [comment]
Cunning thought on this - what would happen if the clipped maxima and minima were set on something wide of 3SD from the median of the whole sequence?

**Comment by johnmackintosh** [comment]
I've been thinking about this.  There are several issues here ,and leaving aside QI considerations ( is a runchart appropriate for this data? If using an SPC chart would these two astronomical points be included in the initial limit calculations?),  I think I want to leave it up to the user to specify appropriate limits and scales, and more importantly, decide what data is appropriate to plot.
  
I have had similar issues with a larger, multi faceted plot where one outlying area meant that the axis limits made it difficult to discern most of the others. 
However, it was straightforward to assign the plot to a variable and then use coord_cartesian() to zoom in.  I also experimented with free scales on the  y axis, which was fine for a quick analytical plot, if not something for onward distribution.

I'll leave this open for now, but I'm not sure its really within the scope of the package to counter this issue (horrible data), which would still be a problem regardless of whatever package/software was used to visualise it.

**Comment by johnmackintosh** [comment]
I still think assigning the plot to a variable and then coord_cartesian() is the way to go, along with removing any obvious outliers that occur at the start / end of the data.
