### ISSUE TITLE
Reversed Y axis

### ISSUE THREAD

**Issue by md0u80c9** [johnmackintosh/runcharter#7]
Another quick suggestion:

If you're using a lot of these charts, you may have some where lower numbers are better and others where higher numbers are better.

You often won't want to rephrase the question in the negative - so you may want to flip the Y axis to represent change.

The two examples I've loaded in earlier issues exemplify that - % of patients reaching the stroke unit within 4 hours (higher number is better); versus median arrival to stroke unit time (lower is better).

If plotting them together it may be nice to be able to flip the axis of one of these so that all the charts should go in the same direction.

**Comment by johnmackintosh** [comment]
https://coolbutuseless.github.io/2019/03/07/custom-axis-breaks-on-facetted-ggplot/

See above for a method of providing custom breaks on the x axis.
Presumably, for a small number of charts you could do something similar for the y axis?
I'm not sure how this could be achieved in a generalised way
